# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "04b079eb6020f4e1bce43e62deaef485"
name = "Titan GEO Lokal"
application_url = "https://geo.titanwalls.de"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products,read_themes,write_content,write_products,write_themes"

[auth]
redirect_urls = ["https://geo.titanwalls.de/auth/callback", "https://geo.titanwalls.de/auth/shopify/callback", "https://geo.titanwalls.de/google/callback"]
